services:
  - type: web
    name: military-asset-system-backend
    root: backend
    runtime: node
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
